# start up with 'docker-compose up -d' to start in background
# update images with 'docker-compose pull' but watchtower is doing this.
# Use 'docker-compose up --detach --build' & 'docker-compose up --detach --build <app>' to not havee to up/down.

version: '3'

#need to perform a 'docker network create proxy' & 'docker network create mainstack'

networks: 

  mainstack:
    external: true
  proxy:
      external: true

  guacnetwork:
    internal: true
  ncdb:
    internal: true

services:

######The Front End######

  traefik:
    image: traefik:chevrotin
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8083:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $USERDIR/docker/traefik/data/traefik.yml:/traefik.yml:ro
      - $USERDIR/docker/traefik/configurations:/configurations:ro
      - $USERDIR/docker/traefik/data/acme.json:/acme.json
      - $USERDIR/docker/traefik/log/access.log:/log/access.log
      - $USERDIR/docker/traefik/log/traefik.log:/log/traefik.log
    environment:
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY
    labels:
      - "traefik.http.routers.traefik-secure.service=api@internal"

  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: always
    networks:
      - proxy
    expose:
      - 9091
    volumes:
      - $USERDIR/docker/authelia/authelia:/var/lib/authelia
      - $USERDIR/docker/authelia/configuration.yml:/etc/authelia/configuration.yml:ro
      - $USERDIR/docker/authelia/users_database.yml:/etc/authelia/users_database.yml
      - $USERDIR/docker/authelia/notification.txt:/tmp/authelia/notification.txt
    environment:
      - TZ=$TZ
      - UID=$PUID
      - GID=$PGID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.middlewares=chain-authelia@file"

  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:latest
    restart: unless-stopped
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    environment:
      - CLIENT_ID=$GOOGLE_CLIENT_ID
      - CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - SECRET=$OAUTH_SECRET
      - COOKIE_DOMAIN=$DOMAINNAME
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$DOMAINNAME
      - URL_PATH=/_oauth
      - WHITELIST=$CLOUDFLARE_EMAIL
      - LOG_LEVEL=warn
      - LOG_FORMAT=text
      - LIFETIME=2592000 # 30 days
      - DEFAULT_ACTION=auth
      - DEFAULT_PROVIDER=google
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth.entrypoints=websecure"
      - "traefik.http.routers.oauth.middlewares=chain-oauth@file"
      - "traefik.http.services.oauth.loadbalancer.server.port=4181"

######Admin-y Type Stuff######

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped

  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $USERDIR/docker/ddclient:/config
    restart: unless-stopped

  librespeed:
    image: linuxserver/librespeed:latest
    container_name: librespeed
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - TZ=$TZ
      - DB_TYPE=sqlite
    labels: 
      - traefik.enable=true
      - traefik.http.routers.librespeed.entrypoints=websecure
      - traefik.http.routers.librespeed.middlewares=chain-oauth@file
    ports:
      - 8085:80
    restart: unless-stopped

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    networks:
      - mainstack
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $USERDIR/docker/portainer:/data
    restart: unless-stopped

  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $USERDIR/docker/duplicati:/config
      - $USERDIR:/source
      - /etc:/system 
    ports:
      - 8200:8200
    restart: unless-stopped

######Dashboards######

heimdall:
  image: linuxserver/heimdall:latest
  container_name: heimdall
  security_opt:
    - no-new-privileges:true
  networks: 
    - mainstack
  ports:
    - 8443:443
    - 8080:80
  volumes: 
    - $USERDIR/docker/heimdall:/config
  environment:
    - PUID=$PUID
    - PGID=$PGID
    - TZ=$TZ
  restart: unless-stopped

######Gameservers#####

  minecraftbe:
    image: toasterlint/minecraft_bedrock:latest
    container_name: minecraftbe
    security_opt:
      - no-new-privileges:true
    volumes:
      - "$USERDIR/docker/minecraftbe:/bedrock-server/config"
      - "$USERDIR/docker/minecraftbe/worlds:/bedrock-server/worlds"
      - "$USERDIR/docker/minecraftbe/valid_known_packs.json:/bedrock-server/valid_known_packs.json"
      - "$USERDIR/docker/minecraftbe/resource_packs/DHBE128LOW:/bedrock-server/resource_packs/DHBE128LOW"
      - "$USERDIR/docker/minecraftbe/resource_packs/HappyVilla:/bedrock-server/resource_packs/HappyVilla"
      - "$USERDIR/docker/minecraftbe/behavior_packs/HappyVilla:/bedrock-server/behavior_packs/HappyVilla"
      - "$USERDIR/docker/minecraftbe/behavior_packs/TameablePa:/bedrock-server/behavior_packs/TameablePa"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    network_mode: host
    restart: unless-stopped

######The Media Server Stack######

  emby:
    image: emby/embyserver:latest
    container_name: emby
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 8096:8096
    volumes:
      - "$USERDIR/docker/emby:/config"
      - "$POOL:/mnt/share1"
    environment:
      - UID=$PUID
      - GID=$PGID
      - GIDLIST=109,998
      - TZ=$TZ
    devices:
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.entrypoints=websecure"
      - "traefik.http.routers.emby.middlewares=chain-default@file"
      - "traefik.http.services.emby.loadbalancer.server.port=8096"
    restart: always

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    ports:
      - "9091:9091"
      - "49650:49650"
      - "49650:49650/udp"
    volumes:
      - "$USERDIR/docker/transmission:/config"
      - "$POOL/torrent:/t-downloads"
      - "$POOL/software:/mnt/samba/software"
      - "$POOL/torrent:/watch"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped
    
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    ports:
      - "8081:8080"
    volumes:
      - "$USERDIR/docker/sabnzbd:/config"
      - "$POOL/newsgroups:/downloads"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    ports:
      - "8989:8989"
    volumes:
      - "$USERDIR/docker/sonarr:/config"
      - "$POOL/tv:/tv"
      - "$POOL/newsgroups:/downloads"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped
    depends_on:
      - nzbhydra2

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    ports:
      - "7878:7878"
    volumes:
      - "$USERDIR/docker/radarr:/config"
      - "$POOL/movies:/movies"
      - "$POOL/newsgroups:/downloads"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped
    depends_on:
      - nzbhydra2

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    ports:
      - "6767:6767"
    volumes:
      - "$USERDIR/docker/bazarr:/config"
      - "$POOL/movies:/movies"
      - "$POOL/tv:/tv"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr

  nzbhydra2:
    image: linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    ports:
      - "5076:5076"
    volumes:
      - "$USERDIR/docker/hydra2:/config"
      - "$POOL/newsgroups:/downloads"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped

  tinymediamanager:
    image: romancin/tinymediamanager:latest
    container_name: tinymediamanager
    security_opt:
      - no-new-privileges:true
    networks: 
      - mainstack
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - "$USERDIR/docker/tinymediamanager:/config"
      - "$POOL/movies:/tmm-movies"
      - "$POOL/tv:/tmm-tv"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped

######Nextcloud######

  db:
    restart: unless-stopped
    image: linuxserver/mariadb:latest
    container_name: nextcloud_db
    security_opt:
      - no-new-privileges:true
    networks:
      - ncdb
    environment:
    - PUID=$PUID
    - PGID=$PGID
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=$NCMYSQL_PASS
    - MYSQL_DATABASE=nextcloud
    - MYSQL_ROOT_PASSWORD=$NCMYSQL_ROOT_PASS
    volumes:
      - $USERDIR/docker/nextcloud/mariadb:/config
      
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - ncdb
    depends_on:
      - db
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $USERDIR/docker/nextcloud:/config
      - $POOL/nextcloud:/data
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.middlewares=chain-nextcloud@file

######Guacamole######

  guacdb:
    restart: unless-stopped
    image: linuxserver/mariadb:latest
    container_name: guacdb
    security_opt:
      - no-new-privileges:true
    networks:
      - guacnetwork
    environment:
    - PUID=$PUID
    - PGID=$PGID
    - TZ=$TZ
    - MYSQL_USER=guacamole_user
    - MYSQL_PASSWORD=$NCMYSQL_PASS
    - MYSQL_DATABASE=guacamole_db
    - MYSQL_ROOT_PASSWORD=$NCMYSQL_ROOT_PASS
    volumes:
      - $USERDIR/docker/guacamole/mariadb:/config

  guacd:
    image: linuxserver/guacd:latest
    container_name: guacd
    security_opt:
      - no-new-privileges:true
    ports:
      - 4822:4822
    networks:
      - guacnetwork
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped

  guacamole:
    container_name: guacamole
    security_opt:
      - no-new-privileges:true
    depends_on:
    - guacd
    - guacdb
    environment:
    -  GUACD_HOSTNAME=guacd
    -  MYSQL_HOSTNAME=guacdb
    -  MYSQL_DATABASE=guacamole_db
    -  MYSQL_PASSWORD=$NCMYSQL_PASS
    -  MYSQL_USER=guacamole_user
    image: guacamole/guacamole:latest
    links:
    - guacd
    - guacdb
    networks:
      - guacnetwork
      - proxy
    ports:
    - 8087:8080
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.guacamole.entrypoints=websecure
      - traefik.http.routers.guacamole.middlewares=chain-guacamole@file
    restart: unless-stopped
