http:
  middlewares:
    chain-basic-auth:
      chain:
        middlewares:
#          - middleware-https-redirect
          - middleware-default-headers
          - middleware-basic-auth
          - middleware-ratelimit
          
    chain-nextcloud:
      chain:
        middlewares:
#          - middleware-https-redirect
          - middleware-default-headers
          - middleware-redirectregex-nextcloud
          - middleware-ratelimit

    chain-default:
      chain:
        middlewares:
          - middleware-ratelimit
          - middleware-default-headers
  