http:
  middlewares:
    chain-basic-auth:
      chain:
        middlewares:
          - middleware-default-headers
          - middleware-basic-auth
          - middleware-ratelimit
          
    chain-nextcloud:
      chain:
        middlewares:
          - middleware-default-headers
          - middleware-redirectregex-nextcloud
          - middleware-ratelimit

    chain-default:
      chain:
        middlewares:
          - middleware-ratelimit
          - middleware-default-headers

    chain-oauth:
      chain:
        middlewares:
          - middleware-ratelimit
          - middleware-default-headers
          - middleware-oauth
      
    chain-authelia:
      chain:
        middlewares:
          - middleware-ratelimit
          - middleware-default-headers
          - middleware-authelia
  
